import { chromium } from 'playwright';
import path from 'path';
const OUT = path.resolve('captures');
const EXE = '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const PROXY = process.env.HTTPS_PROXY || 'http://127.0.0.1:42213';
const sleep = ms => new Promise(r=>setTimeout(r,ms));
const b = await chromium.launch({ executablePath: EXE, args:['--no-sandbox',`--proxy-server=${PROXY}`,'--ssl-version-max=tls1.2','--disable-http2'] });
const ctx = await b.newContext({ viewport:{width:1440,height:900}, deviceScaleFactor:2, ignoreHTTPSErrors:true });
const p = await ctx.newPage();
await p.goto('https://onboardingscheduler.benjaminkrakauer.com/', { waitUntil:'domcontentloaded', timeout:45000 }).catch(()=>{});
await sleep(2500);
const pw = p.locator('input[type="password"]').first();
await pw.click();
await pw.pressSequentially('NYCEM30', { delay: 40 });
await sleep(300);
await p.getByRole('button', { name: /sign in/i }).click({ timeout: 5000 }).catch(async ()=>{ await pw.press('Enter'); });
await sleep(6000);
await p.screenshot({ path: path.join(OUT,'onboarding_in.png') });
console.log('title=', await p.title().catch(()=>null));
console.log('stillPw=', (await p.locator('input[type="password"]').count())>0);
console.log('bodyText=', (await p.evaluate(()=>document.body.innerText).catch(()=>'')).replace(/\s+/g,' ').slice(0,500));
await b.close();
