import { chromium } from 'playwright';
import fs from 'fs'; import path from 'path';
const OUT=path.resolve('captures/callnotes'); fs.mkdirSync(OUT,{recursive:true});
const EXE='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const PROXY=process.env.HTTPS_PROXY||'http://127.0.0.1:42213';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const b=await chromium.launch({executablePath:EXE,args:['--no-sandbox',`--proxy-server=${PROXY}`,'--ssl-version-max=tls1.2','--disable-http2']});
const ctx=await b.newContext({viewport:{width:1440,height:900},deviceScaleFactor:2,ignoreHTTPSErrors:true});
const p=await ctx.newPage();
await p.goto('https://callnotes.benjaminkrakauer.com/',{waitUntil:'domcontentloaded',timeout:45000}).catch(()=>{});
await sleep(2500);
await p.screenshot({path:path.join(OUT,'00_gate.png')});
const pw=p.locator('input[type="password"]').first();
if(await pw.count()>0){ await pw.click(); await pw.pressSequentially('NYCEM30',{delay:35});
  const btn=p.locator('button:has-text("Sign"),button:has-text("Enter"),button:has-text("Continue"),button[type="submit"]').first();
  if(await btn.count()>0) await btn.click({timeout:4000}).catch(()=>{}); else await pw.press('Enter'); await sleep(5000); }
await sleep(3000);
await p.screenshot({path:path.join(OUT,'01_main.png')});
console.log('title=', await p.title().catch(()=>null));
console.log('stillPw=', (await p.locator('input[type="password"]').count())>0);
console.log('bodyText=', (await p.evaluate(()=>document.body.innerText).catch(()=>'')).replace(/\s+/g,' ').slice(0,700));
const nav = await p.$$eval('a,button,[role="tab"]', els=>[...new Set(els.map(e=>(e.innerText||'').replace(/\s+/g,' ').trim()).filter(t=>t&&t.length<30))].slice(0,40));
console.log('nav/buttons=', JSON.stringify(nav));
await b.close();
