import { chromium } from 'playwright';
const EXE='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const b = await chromium.launch({ executablePath: EXE, args:['--no-sandbox','--proxy-server=http://127.0.0.1:42213','--ssl-version-max=tls1.2','--disable-http2'] });
const ctx = await b.newContext({ viewport:{width:1440,height:900}, deviceScaleFactor:1.5, ignoreHTTPSErrors:true, httpCredentials:{ username:'portfolio', password:'BJKPortfolio' } });
const p = await ctx.newPage();
const errs=[]; p.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
const r = await p.goto('https://d3n3019f8cwaj.cloudfront.net/', { waitUntil:'networkidle', timeout:40000 });
console.log('status', r.status(), 'title', await p.title());
const imgs = await p.$$eval('img', a=>a.map(i=>i.naturalWidth));
console.log('image naturalWidths:', imgs.join(','));
await p.locator('#tab-3').click(); await p.waitForTimeout(600);
console.log('tile3 expanded:', await p.locator('#tab-3').getAttribute('aria-expanded'));
await p.screenshot({ path:'captures/live_deployed.png', fullPage:false });
console.log('console errors:', errs.length?errs:'none');
await b.close();
